### ISSUE TITLE
Choosing "Absent" for occurrence under Present/Absent abundance scheme should fire zero abundance = TRUE

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#108]
Choosing "Absent" for occurrence under Present/Absent abundance scheme should fire zero abundance = TRUE in warehouse

**Comment by andrewvanbreda** [comment]
Hi @sacrevert 
This is working for Standard Mode Present/Absent now.

I marked all NPMS/Plant Portal abundance attributes to be abundance counts, so the system now knows they are abundances (rather than just being a standard attribute).

Once that was done, the system applies zero abundance automatically.
I have left the system at its default setting which detects the following values:
['0','none','absent','not seen']

I think because most of our abundance types have minimum 1, this won't make much difference in practice.

However I have a question about "Cell Frequency" abundance. This is a float between 0 and 1.
In that case would 0 be considered a zero abundance value?

I will write some code for Biren to check if anyone has already entered data which should be zero abundance

**Comment by sacrevert** [comment]
>However I have a question about "Cell Frequency" abundance. This is a float between 0 and 1.
In that case would 0 be considered a zero abundance value?

Yes, this would mean that a plant had been observed in zero grid cells of a subdivided quadrat of some sort, so yes, absent/zero abundance would be correct here.

**Comment by andrewvanbreda** [comment]
@sacrevert 
Great so this is setup correctly.
I just need to double check the existing data.

**Comment by andrewvanbreda** [comment]
Hi @kazlauskis 
Am just making this note so you are aware of this for the app.
On the website, some of the code that handles this is in the data_entry_helpers on the website, so I do not think this is something that would be automatic on the app (I think!).
If you need more information about getting this to work on the app, let me know.

**Comment by andrewvanbreda** [comment]
@sacrevert 
As noted above, I checked the existing data and there are no problems relating to incorrect zero abundance on existing data in the database (the zero abundance values hadn't been used apart from test cases).

Note: I did notice quite a few old occurrences (all but one was 2018 or older) which had no abundance at all, but I think those must of originated from the days where abundance wasn't mandatory on the data entry form.
These were not zero abundance which is right.

@sacrevert @kazlauskis 
I am unassigning myself from this now, please close once you are happy the app will behave correctly.
