### ISSUE TITLE
New accounts still require approval -- can we remove this?

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#110]
I don't think we need to approve every registration on the Plant Portal site -- can we remove this aspect of registration?

**Comment by andrewvanbreda** [comment]
Hi @sacrevert

I have to say, I am utterly bemused by this.
I had the same trouble as you this morning on Plant Portal (also on a multidev site).
The settings were correct though, I fiddled with a few settings and still had same issue.
Then suddenly the problem went away (perhaps after cache clearing).
I did change one settings (not related to this) where the password is now set after the email is received, not on the initial registration form. That is now like NPMS.
So the problem is now gone, but I don't know why.
Given this erratic behaviou,r I would be advise that you test to confirm you are happy and not take my word for it.

**Comment by sacrevert** [comment]
Seems to be working now for a test account I created
