### ISSUE TITLE
Will squares be reused between projects?

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/plantportal#17]
@sacrevert 
I was just looking at how to do various things related to the plots, and a question occurred to me.

We discussed before about plots. I think we decided these can optionally be attached to a parent square if needed

Now there is a little detail about this that is important for coding actually.

So we have a OSGB square, let's call it
AA11

Now can this be reused between projects, or would square AA11 be saved a separate location for each project that wanted a square in this position?

This may seem like a little detail, but the programming implications are quite large.

**Comment by sacrevert** [comment]
Things can be nested at any regularly used scales ultimately. This could be 1km square, 10km square, vide-county or country. I think actually that standard mode doesn't necessarily need square ownership in the same way that NPMS mode does, because we have things like plot groups and projects to organise plots and samples anyway. I think, really, that for standard mode plots the information about overlap/nesting is more akin to the layers that are reported in NPMS (like SSSIs, NNRs etc.). That is, it's useful for the user to see this information, but standard mode doesn't need all the square ownership/allocation stuff that NPMS mode has

**Comment by andrewvanbreda** [comment]
Issue doesn't need to be open anymore, squares are attached to projects for NPMS type, like plots are attached to projects for standard mode.
(on NPMS type the plots are only attached to the project via the square they are attached to)
