### ISSUE TITLE
Add/edit square doesn't have irish grid (epsg:29902)

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#31]
I think we dealt with this on the NPMS website previously, but at the moment a user can select a British 1 km square within Ireland.
(i) it would be good to disallow this or have it generate a warning
(ii) it would be good if it could default to the irish grid over ireland, and the british grid over GB (or follow whatever we did for the NPMS website)
(iii) would also be good to check that uploader can deal with Irish grid

**Comment by andrewvanbreda** [comment]
@sacrevert 
This is now fixed on the Add/Edit Square screen (using same code as NPMS). 
I am not sure how to deal with this with the importer though.
The problem is I think some OSGB grid references are still valid inside some of the Irish boundary. The square importer is just based on the standard Indicia importer.
It would need some extra logic for it to say "This is valid, but actually it isn't, so need to stop the import".
This would be a huge amount of work I think.
Let me know your thoughts.

**Comment by sacrevert** [comment]
Yes, I can see that. Technically speaking the British grid is not invalid over Irish land. I think we can just assume that anyone using the importer would know what they are doing. More difficult to mess it up there compared to the interactive interface
