### ISSUE TITLE
"My samples" label/page when project admin

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#35]
For user "Sarah Shuttleworth" and project `group_id=2134` the user is a group admin, so the text link My samples on the "My projects" page, and here on the actual "my samples" page (https://plantportal.ceh.ac.uk/my-samples-npms-mode?group_id=2134&implicit=f)
should these actually be labelled "All samples", as I assume they display all the project samples rather than just the admins?

**Comment by andrewvanbreda** [comment]
@sacrevert @BirenRathod 
Hi Biren,
Looking at this, the Create Project page is also missing from the main menu (so new ones can't be added either)
I have checked, and the Create/Edit Project page has been deleted.
Biren: Could this be the same problem as yesterday with the permissions?
I have checked the node.js files and can tell it is node 30 that is missing.
Obviously we don't want this to be widespread across websites.

**Comment by andrewvanbreda** [comment]
Infor now correctly added to #36

**Comment by andrewvanbreda** [comment]
@sacrevert 
The way this currently works is they do get the "My Samples" page.
This would be difficult to alter, as the project permissions are designed so that admins for projects can see everything.
I could perhaps remove than link if the user is detected as a website administrator (as opposed to a project administrator)

There is an All Samples link, but it is currently called "Samples administration".
I could change this easily for new projects if you wanted, but I think changing it on existing projects would need a database hack.

Let me know your thoughts having read these notes (or close the issue if you are happy)

**Comment by sacrevert** [comment]
Happy to close if labelling is accurate. Not worth changing I think
