### ISSUE TITLE
Add Location importer to Plant Portal

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/plantportal#4]
Plant Portal needs a location importer that allows an administrator to import plots into a specific project.
This importer must also be able to optionally support import of parent squares.

(Note: It may be that the standard Indicia import has enough functionality to support this without alteration)

**Comment by andrewvanbreda** [comment]
AVB: Note to myself, looks like the Indicia Location importer will need enhancing to allow groups_locations import, so a project can be assigned to each location being imported.

**Comment by andrewvanbreda** [comment]
AVB Note: Required change committed to Develop branch. This code is just a change to the groups_location.php model, so will come through next time warehouse is updated.
Think should just need to update the language file on the location importer so the Group is now call Project.

**Comment by andrewvanbreda** [comment]
AVB not to myself: Added node.11.js which includes code that changes Group to be Project inside the importer

**Comment by andrewvanbreda** [comment]
"NPMS Mode - Square importer" now correctly links to NPMS Mode projects and is only available to NPMS Mode project administrators only (instead of website administrators).
Also people can't just import squares onto any old project anymore, has to be their own.

**Comment by andrewvanbreda** [comment]
@sacrevert 
Hi Oli,

I notice this issue originally talks about plot imports.
Is that something you still want?
And if so do you need plot imports for Standard Mode, NPMS Mode, or both?

**Comment by sacrevert** [comment]
@andrewvanbreda I think the idea was that plot imports would only be for Standard mode, because the NPMS approach assumes that users would go in and create their own plots interactively.

I would therefore say that, whilst this is still desirable for Standard mode, it's not an immediate priority (unless of course it is now trivial to implement because of the work you have done for importing squares, in which case we could just implement for Standard mode plots as well whilst you have it in your mind). If it's a bit more involved, then we should wait. We could close this item and make a new one, or leave it open with this outstanding element, whichever you think is best.

**Comment by andrewvanbreda** [comment]
@sacrevert 
Leave this open. 
It would be quite trivial to fix, just a few hours, but I will do the other bits of Standard Mode first, as quite a few small issues could use up time.

**Comment by sacrevert** [comment]
@andrewvanbreda I think this should be closed now that we have #54, no?
