### ISSUE TITLE
Missing link options under my projects

### ISSUE THREAD

**Issue by NPMSSupport** [BiologicalRecordsCentre/plantportal#41]
If I view my project in amongst the list of all projects, then I can see the options Join Project, Invite people to join project, manage membership and edit project details. However if I view my project under My projects then these are not available. I can simply put in my training package that those options can only be linked to via the all projects page but I wasn't sure if at some point it might be good to have these available under my project too. @andrewvanbreda

**Comment by sacrevert** [comment]
Thanks @NPMSSupport 
@andrewvanbreda  this kind of links to this one (https://github.com/BiologicalRecordsCentre/plantportal/issues/34) and another issue. I think the issue here is that the "people" type column could be added to the My Projects page, so that project admins see them there too. I suppose an issue is that ordinary project member would see nothing in this column on the My Projects page; I think this is OK in the short term (perhaps in the longer term they could see a "leave project" option here. Let me know what you think, and I can open other issues accordingly

**Comment by sacrevert** [comment]
@NPMSSupport For the moment I would just note that currently these options are only available via All Projects for project admin, but that this will be updated in the future

**Comment by andrewvanbreda** [comment]
@sacrevert @NPMSSupport 
Close if happy. Note this is medium in Github, but was noted as urgent in our email conversation
