### ISSUE TITLE
Account creation issue for one user

### ISSUE THREAD

**Issue by NPMSSupport** [BiologicalRecordsCentre/plantportal#47]
@andrewvanbreda Tim Corner from Bristol records centre is having issues creating an account. It has brought up the indicia logins he has for irecord and BRERC and he wasn't sure how to move forward on that or what to tick or not tick.

**Comment by sacrevert** [comment]
Do we need some guidance text on the create account page whereby it tells people with existing email addresses in the indicia system how best to proceed?

**Comment by DavidRoy** [comment]
There is a bit of text on the BNM online site, for registering and need for the same email address - https://www.butterflyrecording.org/user/register

**Comment by andrewvanbreda** [comment]
@DavidRoy @NPMSSupport @sacrevert 
This is Indicia trying to make sure the user is linked to the same Warehouse account as their other website registrations.
The main advantage of this is that their Record account can then become a central hub for their activity.

This is built into Indicia and nothing has been customised for Plant Portal regarding this.
I think if unclear, perhaps it should be raised as a general Indicia issue, any functionality that Indicia shows to the user should be self-explanatory.

**Comment by sacrevert** [comment]
@andrewvanbreda is it straightforward just to add some text as David suggests? I appreciate that the way the account options are presented might be a general indicia issue, but in the interim just some guidance to the user (e.g. "Please select your main indicia account" or whatever) would be helpful to reassure a user that they can proceed without the world falling in?

**Comment by andrewvanbreda** [comment]
@sacrevert Yes can do that simply to improve situation for Plant Portal

**Comment by sacrevert** [comment]
@andrewvanbreda Thanks. I would go with something like this as per David's butterfly example:

>Thank you for registering to use the Plant Portal. This site allows you to submit plant occurrence data for plot-based habitat recording. These records form a shared pool of data with those submitted via the NPMS, iRecord, and other indicia-based systems. If you wish to maintain all your records together from these different sources, please make sure that you register with the same email address on each system.

However, I'm not sure this is entirely accurate, because i thought Plant Portal was set-up so that occurrence records were not shared with iRecord, for, for example, verification. Can you confirm that a user can see their plant portal occurrence records in their iRecord, or other, site, even though the data are not exposed for verification through that (or any other) system?

**Comment by DavidRoy** [comment]
Maybe good to name NPMS specifically given the links?

**Comment by andrewvanbreda** [comment]
@DavidRoy @sacrevert 
Yes Plant Portal data doesn't get shown on the iRecord website (I checked, although this can be changed at your end if you wish).
So I think this means it will not go through the verification system, as those are screens are on iRecord.

Although it doesn't go through the verification system, data would still be processed by any modules that the Warehouse is running. I suppose the obvious one I can think of (only because I wrote it) is Species Alerts, although I don't know if there are any invasive species included on Plant Portal.
I am not sure what other modules might be running. It depends on how the individual modules are configured whether it processes the data.

The other thing to note, is although in Plant Portal, we talk about "NPMS Mode", it has nothing to do with NPMS from the computing point of view other than they are based on each other.
The final (obvious) consideration is that although Plant Portal data is not shown on on iRecord, it does get all stored in the same Warehouse.

So I think if you let me know the final wording considering the above, I will put it on the site.

**Comment by sacrevert** [comment]
@andrewvanbreda @DavidRoy 
Thanks Andy for the info; however, I'm not sure from what you write whether this bit of what I wrote has any relevance or not for the user?
>If you wish to maintain all your records together from these different sources, please make sure that you register with the same email address on each system.

GIven what you say, is there actually any practical impact from, e.g., the initial user mentinoed at the top of this thread choosing to link to their iRecord account rather than BRERC, or NPMS over iRecord, or whatever... Apologies for my ignorance!

**Comment by andrewvanbreda** [comment]
@sacrevert 
Sorry this is confusing. What I will do instead of us messaging back and forth, I will suggest some text, and you can tell me if it is any good to use.

I think there are a few things that are confusing
1. Yes you are right, that there is currently minimal impact on Plant Portal from these other systems from the user's point of view.
2. This could change in the future, say if Plant Portal data became available in iRecord.
3. Indicia will automatically try to make the connection anyway, so the user might get that merger message we spoke about
4. The identification of the user to the other systems could be important for reporting.

Given this, I would perhaps suggest the following (I also removed the reference to Indicia, not sure users will know what that is?)

Feel free to suggest changes.

Thank you for registering to use the Plant Portal. This site allows you to submit plant occurrence data for plot-based habitat recording. These records form a shared pool of data with those submitted via the NPMS, iRecord, and other systems. To allow us to make best use of your data, please make sure that you register with the same email address on each system.

**Comment by sacrevert** [comment]
Thanks @andrewvanbreda 
Your suggested message sounds fine to me.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Does the Markup module need to be installed to do this?

**Comment by BirenRathod** [comment]
@andrewvanbreda I'm not clear, so can you explain me the purpose of using Markup module?

**Comment by andrewvanbreda** [comment]
@BirenRathod 
To allow free text instructions to be placed onto registration page.

It doesn't have to Markup module, what we want is same thing as on this site

https://www.butterflyrecording.org/user/register

 but instead it should say the following for Plant Portal
"Thank you for registering to use the Plant Portal. This site allows you to submit plant occurrence data for plot-based habitat recording. These records form a shared pool of data with those submitted via the NPMS, iRecord, and other systems. To allow us to make best use of your data, please make sure that you register with the same email address on each system."

**Comment by BirenRathod** [comment]
@andrewvanbreda you don't need Markup module. It is easy to do by adding field here -> admin/config/people/accounts/fields.

Can you able to do it?

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Yep that is where I was looking, but are any of those available field types actually read-only text? In Drupal 7 that is what the Markup module was for.
Do you know which available field type I should use then in Drupal 9 for the equivalent?

**Comment by BirenRathod** [comment]
@andrewvanbreda Unfortunately none of them available to do that job, so I have install Markup module now. please enable it. Thanks for your suggestion.

**Comment by andrewvanbreda** [comment]
@sacrevert @NPMSSupport 
This instruction is now available at top of the registration form.
I thought it looks better if I put the last sentance in bold about using same email address, let me know if you prefer that as standard text.

Also note that for most users they will only see this on the registration form, but because you are administrators you will also see it on the My Account page (as you have rights to see everything). Please ignore that, normal users won't get that issue

Close if happy

@BirenRathod Thanks for the Markup installation. I also enabled Field Permissions which was already installed.
