### ISSUE TITLE
Can project admins have the ability to edit plots they didn't create?

### ISSUE THREAD

**Issue by NPMSSupport** [BiologicalRecordsCentre/plantportal#50]
This would be useful for many organisations. Only project admins obviously and not after data has been submitted.

**Comment by andrewvanbreda** [comment]
Hi @NPMSSupport @sacrevert 
Although market as "low", I have addressed this issue as it is at a core of a major problem with the Plant Portal system that much of the administration was pushed to the website administrator rather than the project manager.
This problem would also have been at the core of Standard Mode once it goes live also.
I have made many changes to the way the system works that are invisible to fix this problem.
As a natural result of this Project managers can also now manage squares as well as plots they didn't create.
I have tried my best to deploy these in a sensible fashion, but there are so many changes it is very hard to be sure everything is right.

Leave issue open for now and we can close once sure system is operating correctly.

**Comment by andrewvanbreda** [comment]
Not working properly.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
If you could pull this report whenever you get chance please that would be great thanks
plant_portal/pp_locations_list.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda That report have gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
That is great thanks :)

**Comment by andrewvanbreda** [comment]
Sorry @BirenRathod 
I made a mistake with the commit, and left some code commented out which is breaking it.
Would you be able to pull the report again please.

**Comment by BirenRathod** [comment]
@andrewvanbreda Done.

**Comment by andrewvanbreda** [comment]
Thanks @BirenRathod for super quick response :)

**Comment by andrewvanbreda** [comment]
Fixed.
Standard users can only edit own plots, not after data submitted.
Project administrator users can edit any plot on projects they are an administrator for, not after data submitted.

**Comment by sacrevert** [comment]
Thanks @andrewvanbreda , presumably, the URL edit hack is still generally available for editing plots (regardless of data submitted). I know we don't advertise this, but would be useful to have this confirmed either way.

**Comment by andrewvanbreda** [comment]
@sacrevert 
Yes in this case, there is no strict enforcement.
You can change the summary_mode param in the URL.
