### ISSUE TITLE
Potential bug with deleting a square

### ISSUE THREAD

**Issue by NPMSSupport** [BiologicalRecordsCentre/plantportal#56]
When deleting a square there is currently an error message after hitting delete button ‘This page needs a group_id URL parameter.’  I think it would be logical for the user to be returned to the Square list after deleting a square, which doesn’t happen at the moment!

**Comment by NPMSSupport** [comment]
@andrewvanbreda

**Comment by andrewvanbreda** [comment]
@sacrevert @NPMSSupport 
Ok, can see what is happening. I will have a fiddle with the page when it isn't being used.
It is because the edit square page doesn't care about the project, it just says "I am editing this square" to itself.
But the problem with that is that although it doesn't need to know, the next screen does, so I will alter that to pass it through.
For now I have changed it to return to All Projects, not ideal, but better than nasty message.

**Comment by andrewvanbreda** [comment]
@sacrevert 
I personally think this one should be lower than high now, and I will put some Standard Mode work in front of it.
As mentioned it should not error anymore, and isn't a very simple fix.
Unless I hear otherwise, I will be treating this as low but I will leave you to set the status. Feel free to message to disagree with that.

**Comment by NPMSSupport** [comment]
Great thanks @andrewvanbreda, I agree better than an error message

**Comment by andrewvanbreda** [comment]
I don't know when this was completely fixed, but this actually returns to the List Squares page properly. Maybe fixed as result of another issue.
Closing.
