### ISSUE TITLE
Data entry page not working

### ISSUE THREAD

**Issue by SarahSaxifrage** [BiologicalRecordsCentre/plantportal#65]
![image](https://user-images.githubusercontent.com/108128512/178002397-dc2ed0bc-0fa5-44c6-b475-f45874f0b6df.png)
The data entry pages and other pages are not working, help
@andrewvanbreda @sacrevert

**Comment by andrewvanbreda** [comment]
@SarahSaxifrage 
I will look now

**Comment by andrewvanbreda** [comment]
@sacrevert @SarahSaxifrage 
Fixed.
This was caused by really annoying feature of Drupal 9 which auto-generates the URL address of a page.
So the system changed the URL even though I had only been altering the map.
As I only altered the map I hadn't considered this would happen.
I will also fix the test site.
Please close if happy with result.

**Comment by andrewvanbreda** [comment]
I have switched off the auto URL, so this won't happen in future.

**Comment by andrewvanbreda** [comment]
Let me know if there are other pages not working, I tried some others without trouble
