### ISSUE TITLE
"Create project" button not working

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#93]
I have filled in all fields on this page as a test project using my admin account, and nothing happens.

**Comment by andrewvanbreda** [comment]
Hi @sacrevert ,

I do not understand this issue yet, it looks like the error is occurring inside Indicia general code rather than Plant Portal's which is odd because the page I mention below works.

I do have a clone of the page you can use temporarily. 
This page is (supposed) to be identical, apart from the links that are automatically setup for the project are displayed on screen (so I can debug).
This page seems to be working, so if you do need to urgently set up a project you can use this.

You will see lots of extra boxes appear on page when you select the projec type, but you can ignore these.

https://plantportal.ceh.ac.uk/create-edit-project-developer-version

**Comment by sacrevert** [comment]
Not urgent for me, I was just wanting to test some other things and looking to create a test project. Cheers

**Comment by andrewvanbreda** [comment]
@sacrevert 
Bit of an odd one, I compared the configuration with my developer version of the page (which is fine).
So I simply re-saved the Edit Tab on the standard Created Project page (without making changes) and it started working.
Perhaps this can be closed after the demo tomorrow (assuming it is still working)

**Comment by sacrevert** [comment]
Seen working on live
